# numpy Study

A collection of useful online resources and scripts for plotting with numpy.

Resources
1. [Quickstart Tutorial](https://numpy.org/doc/stable/user/quickstart.html)
2. [Other Learn Resources](https://numpy.org/learn/)

# Scripts

### Code from Quick Start Course
#### An Example

In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
# properties of the array
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
type(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15


numpy.ndarray

#### Array Creation

In [8]:
# Array of floats
b = np.array([1.2,3.5,5.1])
print(b.dtype)
# Array of complex
c = np.array([[1,2],[3,4]], dtype=complex)
print(c)

float64
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [11]:
num0 = np.zeros((3,4))
print(num0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
num1 = np.ones( (2,3,4), dtype=np.int16 )
print(num1)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [14]:
from numpy import pi
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)

#### Basic Operations

In [15]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
print(c)

[20 29 38 47]


In [16]:
print(b**2)

[0 1 4 9]


In [18]:
alog = a < 35
print(alog)

[ True  True False False]


In [20]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A)
print(B)
# element wise multiplication
print(A*B)
# matrix multiplication
print(A@B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [21]:
A *= 3
print(A)

[[3 3]
 [0 3]]


In [22]:
B += A
print(B)

[[5 3]
 [3 7]]


#### Indexing, Slicing and Iterating

In [23]:
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [24]:
print(a[2])
print(a[2:5])

8
[ 8 27 64]


In [26]:
# set every second element to 1000.0
a[:6:2] = 1000.0
print(a)
# reverse direction of a
print(a[: :-1])

[1000    1 1000   27 1000  125  216  343  512  729]
[ 729  512  343  216  125 1000   27 1000    1 1000]


In [27]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [28]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [29]:
print(b[2,3])

23


In [30]:
print(b[0:5,1])

[ 1 11 21 31 41]


In [31]:
print(b[:,1])

[ 1 11 21 31 41]


In [32]:
print(b[1:3,:])

[[10 11 12 13]
 [20 21 22 23]]


In [33]:
print(b[-1])

[40 41 42 43]


In [34]:
# Iteration over rows
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [35]:
# Iterate over elements
for elem in b.flat:
    print(elem)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


#### Shape Manipulation

In [44]:
a = np.arange(12).reshape(3, 4)
print(a.shape)

(3, 4)


In [45]:
print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [46]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
print(a.reshape(6,2))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [49]:
print(a.T)
print(a.T.shape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [52]:
a.resize(6,2)
print(a)
 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [51]:
# -1 means automatically calc other dimension
print(a.reshape(2,-1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


#### Stacking Together Different Arrays

In [57]:
# stacking horizontally and vertically
rg = np.random.default_rng(1)
a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[5. 9.]
 [1. 9.]
 [3. 4.]
 [8. 4.]]
[[5. 9. 3. 4.]
 [1. 9. 8. 4.]]


In [58]:
a = np.floor(10*rg.random((2,12)))
print(np.hsplit(a,3))

[array([[5., 0., 7., 5.],
       [7., 2., 4., 9.]]), array([[3., 7., 3., 4.],
       [9., 7., 5., 2.]]), array([[1., 4., 2., 2.],
       [1., 9., 5., 1.]])]


#### Copies and Views

In [60]:
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11]])
b = a[:,1]
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 5 9]


In [61]:
b = np.arange(3).reshape(1, 3)

In [62]:
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2]]


In [64]:
b = a
b.resize(2,6)
print(a)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [69]:
# copy method makes a copy that won't change
d = a.copy()
print(d)
d[:,3] = np.array([0,0])
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  0  4  5]
 [ 6  7  8  0 10 11]]


#### Broadcasting

In [5]:
# behaviour when multiplying arrays of the same size or array x scalar is predictable
a = np.array([1.0, 2.0, 3.0])
b = 2.0
print(a * b)
c = np.array([3.0,4.0,2.5])
print(a*c)

[2. 4. 6.]
[3.  8.  7.5]


In [13]:
d = np.array([[2.0,2.0,4.0],[2.0,1.0,3.0]])
print(d)
print(a*d)
print(np.shape(d))
print(np.shape(a))

[[2. 2. 4.]
 [2. 1. 3.]]
[[ 2.  4. 12.]
 [ 2.  2.  9.]]
(2, 3)
(3,)


In [20]:
# more interesting broadcasting idea
a = np.array([[1.0,2.0,3.0]])
print(np.shape(a))
b = np.array([[4.0],[5.0]])
print(np.shape(b))
a+b

(1, 3)
(2, 1)


array([[5., 6., 7.],
       [6., 7., 8.]])

Dimensions must either be equal or one of them must be one

#### Advanced Indexing and Index Tricks

In [4]:
a = np.arange(12)**2
print(a)
i = np.array([1, 1, 3, 8, 5])
j = np.array([[3, 4], [9, 7]])
print(a[i])
print(a[j])

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


In [19]:
palette = np.array([[0, 0, 0],         # black
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])
image = np.array([[0, 1, 2, 0],        # refers to first dimension from above e.g. rows from above,                                    
                  [0, 3, 4, 0]])       # 0 - black, 1 - red, 2 green 0 black first row here. The 0 - black,
                                       # 3 - green, 4 - blue, 0 black

print(palette.shape)
newimage = palette[image]
print(newimage[0])
print(newimage[1])

(5, 3)
[[  0   0   0]
 [255   0   0]
 [  0 255   0]
 [  0   0   0]]
[[  0   0   0]
 [  0   0 255]
 [255 255 255]
 [  0   0   0]]


#### creating filter - transport modelling

In [5]:
rg = np.random.default_rng(1)
costs = np.floor(10*rg.random((3,3)))
print(a)

[[5. 9. 1.]
 [9. 3. 4.]
 [8. 4. 5.]]


In [10]:
odpairs = np.array([[1,0,0],[1,0,1],[1,1,0]])
print(odpairs)

[[1 0 0]
 [1 0 1]
 [1 1 0]]


In [11]:
print(odpairs*fil)

[[1 0 0]
 [1 0 1]
 [1 1 0]]


In [15]:
fil = np.ones((3,3)) - 0.05*odpairs
print(fil)

[[0.95 1.   1.  ]
 [0.95 1.   0.95]
 [0.95 0.95 1.  ]]
